package exceptions

import exceptions.AuthException

class AlreadyRegisteredException() : AuthException("Already registered");
